name: i18n extraction
on: [push]
  # push:
  #   branches: [ general-devel ]
jobs:
  extract:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            3.1.x
            6.0.100

      - name: Run i18n checking/extraction script
        run: ./.github/scripts/i18n.sh
        shell: bash
